name: Setup exiftool
description: |
  Install exiftool on the runner. This is a composite action that checks the OS and installs the appropriate package.
runs:
  using: "composite"
  steps:
    - run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          sudo apt-get update && sudo apt-get install -y libimage-exiftool-perl
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          brew install exiftool
        fi
      shell: bash